apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp1
    image: nginx
    volumeMounts:
    - mountPath: /web
      name: webapp
  volumes:
  - name: webapp
    hostPath:
      path: "/mnt/webapp"
